### PR TITLE
Add TAIR10 map coordinates for ArabMAGIC

### PR DESCRIPTION
**Pull request by tavareshugo**
Dear @kbroman,

(first of all, thanks so much for developing this package and parsing these data into a `cross2` object, really useful!)

Before realising you had these, I was doing [something similar](https://github.com/tavareshugo/atMAGIC) in parallel, although I was using the data from http://mtweb.cs.ucl.ac.uk/mus/www/magic/. It's a bit confusing, as they have slightly different sets of missing genotypes (both for the founders and the MAGICs), so I guess your option of using the actual published data seems sensible. 

However, the marker coordinates provided in Gnan 2014 are for an old version of the Arabidopsis genome assembly (TAIR8), and having up-to-date coordinates (TAIR10) would be useful if one wants to look for candidate genes, etc. 

I therefore adapted your `convert_data.R` script to use these coordinates instead, in case you would consider revising it and merging with your repo. (also, you're left with 1251 markers instead of 1027)

I realise you're aiming to publish the paper using these data, so I understand if this would affect the reproducibility of your analysis. 

(as an aside, I suspect that Gnan 2014 might have used the data from [Richard Mott's server](http://mtweb.cs.ucl.ac.uk/mus/www/magic/) for their scans, which is in the format required by the `happy.hbrem` package that they use, and that may explain some of the differences seen in [your paper](https://www.biorxiv.org/content/early/2018/11/26/414748)). 

Cheers,
hugo

### CODE REVIEW

**Comment by kbroman** [comment]
@tavareshugo: Thanks for doing this! I think I think I should try to include both the old map and the new map, since it seems like the old map was what was used in Gnan et al, and since I'm using it in my R/qtl2 paper. But I'll get your work in here somehow.

**Comment by kbroman** [comment]
Finally looking back at this; I thought I'd dump the full genotypes and founder genotypes into files, and then make separate map files, TAIR8 and the newer one.

But while you mentioned TAIR10, but the files all say the build is TAIR9. And [that source page](http://mtweb.cs.ucl.ac.uk/mus/www/magic/) says, cryptically, "TAIR9/TAIR10". Should I just call them TAIR9?

**Comment by kbroman** [comment]
Hi, @tavareshugo, I reworked your code so that I could include side-by-side versions of the data, since I'd used the TAIR8 map in the [R/qtl2 paper](https://doi.org/10.1534/genetics.118.301595).

**Comment by tavareshugo** [comment]
Thanks @kbroman. Just a follow up about the TAIR9/TAIR10 ambiguity. The Arabidopsis genome version TAIR10 was an update to the gene annotation, the genome assembly itself didn't change, so physical locations in TAIR9 and TAIR10 versions are the same. Calling it `tair9` like you did should be fine, I imagine. :+1:

**Pull request closed without merging**
